#**DATA PROCESSING**

In [1]:
#import libraries
import pandas as pd
import numpy as np

In [2]:
#Upload dataset

from google.colab import files
files.upload()

Saving heart.csv to heart (5).csv


{'heart.csv': b'\xef\xbb\xbfage,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target\r\n63,1,3,145,233,1,0,150,0,2.3,0,0,1,1\r\n37,1,2,130,250,0,1,187,0,3.5,0,0,2,1\r\n41,0,1,130,204,0,0,172,0,1.4,2,0,2,1\r\n56,1,1,120,236,0,1,178,0,0.8,2,0,2,1\r\n57,0,0,120,354,0,1,163,1,0.6,2,0,2,1\r\n57,1,0,140,192,0,1,148,0,0.4,1,0,1,1\r\n56,0,1,140,294,0,0,153,0,1.3,1,0,2,1\r\n44,1,1,120,263,0,1,173,0,0,2,0,3,1\r\n52,1,2,172,199,1,1,162,0,0.5,2,0,3,1\r\n57,1,2,150,168,0,1,174,0,1.6,2,0,2,1\r\n54,1,0,140,239,0,1,160,0,1.2,2,0,2,1\r\n48,0,2,130,275,0,1,139,0,0.2,2,0,2,1\r\n49,1,1,130,266,0,1,171,0,0.6,2,0,2,1\r\n64,1,3,110,211,0,0,144,1,1.8,1,0,2,1\r\n58,0,3,150,283,1,0,162,0,1,2,0,2,1\r\n50,0,2,120,219,0,1,158,0,1.6,1,0,2,1\r\n58,0,2,120,340,0,1,172,0,0,2,0,2,1\r\n66,0,3,150,226,0,1,114,0,2.6,0,0,2,1\r\n43,1,0,150,247,0,1,171,0,1.5,2,0,2,1\r\n69,0,3,140,239,0,1,151,0,1.8,2,2,2,1\r\n59,1,0,135,234,0,1,161,0,0.5,1,0,3,1\r\n44,1,2,130,233,0,1,179,1,0.4,2,0,2,1\r\n42,1,0,140,226,

In [3]:
#read data

data = pd.read_csv("heart.csv")
data.head

<bound method NDFrame.head of      age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0     63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1     37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2     41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3     56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4     57    0   0       120   354    0  ...      1      0.6      2   0     2       1
..   ...  ...  ..       ...   ...  ...  ...    ...      ...    ...  ..   ...     ...
298   57    0   0       140   241    0  ...      1      0.2      1   0     3       0
299   45    1   3       110   264    0  ...      0      1.2      1   0     3       0
300   68    1   0       144   193    1  ...      0      3.4      1   2     3       0
301   57    1   0       130   131    0  ...      1      1.2      1   1     3       0
302   57    0   1       130   236  

##Check missing data

In [4]:

data.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

##Split data


In [5]:
from sklearn.model_selection import train_test_split

X = data.drop('target', axis=1)
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, test_size=0.2, random_state=0)

##Normalize data

In [6]:
#Scaling train data
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
col_to_scale = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']
X_train[col_to_scale] = sc.fit_transform(X_train[col_to_scale])

In [7]:
X_train

age  sex  cp  trestbps      chol  ...  exang   oldpeak  slope  ca  thal
74  -1.327733    0   2 -0.574125 -0.632674  ...      0 -0.724609      1   0     2
153  1.249032    0   2  0.831066  0.585437  ...      0 -0.892493      1   1     2
64   0.352766    1   2  0.479768 -0.670155  ...      0 -0.892493      2   0     2
296  0.912932    0   0 -0.457026 -0.932517  ...      1 -0.892493      1   0     2
287  0.240733    1   1  1.299463 -0.276611  ...      0 -0.892493      2   1     2
..        ...  ...  ..       ...       ...  ...    ...       ...    ...  ..   ...
251 -1.327733    1   0  0.011371  0.004491  ...      1 -0.808551      1   4     3
192 -0.095367    1   0 -0.691224 -1.101178  ...      0  0.282698      1   1     3
117  0.128699    1   3 -0.691224 -1.007478  ...      0  0.702409      1   0     3
47  -0.879600    1   2  0.362669  0.191893  ...      0 -0.892493      2   0     2
172  0.352766    1   1 -0.691224  0.697878  ...      0  0.618467      1   0     2

[242 rows x 13 columns]

In [8]:
#Scaling test data
X_test[col_to_scale] = sc.transform(X_test[col_to_scale])

In [11]:
X_test

age  sex  cp  trestbps      chol  ...  exang   oldpeak  slope  ca  thal
225  1.697165    1   0  0.772516 -1.363541  ...      1  1.290005      0   0     3
152  1.024965    1   3  2.236257 -0.370312  ...      0 -0.388840      1   0     3
228  0.464799    1   3  2.236257  0.772838  ...      0 -0.724609      1   0     3
201  0.576832    1   0 -0.398476  0.210633  ...      1  1.457889      1   1     3
52   0.800899    1   2 -0.105728 -0.295351  ...      0  0.618467      1   3     3
..        ...  ...  ..       ...       ...  ...    ...       ...    ...  ..   ...
146 -1.215700    0   2 -0.808324 -0.089209  ...      0 -0.640667      1   1     2
302  0.240733    0   1 -0.105728 -0.201650  ...      0 -0.892493      1   1     2
26   0.464799    1   2  1.065265 -0.651414  ...      0  0.450583      2   0     2
108 -0.543500    0   1 -0.691224 -0.051729  ...      0  0.030871      2   0     2
89   0.352766    0   0 -1.862217  0.023232  ...      0 -0.053071      1   0     2

[61 rows x 13 columns]

# **TRAIN MODEL**

##*create print result funtion*

In [9]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

def print_result(model,pred, X_train, y_train, X_test, y_test):     
        model_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
        print("Train Result:\n================================================")        
        print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{model_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")
        

## **Logistic Regression**

In [10]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(solver='liblinear')
lr_model.fit(X_train, y_train)
lr_pred = lr_model.predict(X_test)
print_result(lr_model,lr_pred, X_train, y_train, X_test, y_test)



Train Result:
Accuracy Score: 85.25%
_______________________________________________
CLASSIFICATION REPORT:
                   0          1  accuracy  macro avg  weighted avg
precision   0.875000   0.837838  0.852459   0.856419      0.854287
recall      0.777778   0.911765  0.852459   0.844771      0.852459
f1-score    0.823529   0.873239  0.852459   0.848384      0.851237
support    27.000000  34.000000  0.852459  61.000000     61.000000
_______________________________________________
Confusion Matrix: 
 [[21  6]
 [ 3 31]]



###R*esult with new input*

In [11]:
#Result with new input
new_input = [37,	1,	2,	130,	250,	0,	1,	187,	0,	3.5,	0,	0,	2	]
lr_model.predict([new_input])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  "X does not have valid feature names, but"


array([1])

## **Support Vector machine**

In [12]:
from sklearn.svm import SVC


svm_model = SVC(kernel='rbf', gamma=0.1, C=1.0)
svm_model.fit(X_train, y_train)
svm_pred = svm_model.predict(X_test)

print_result(svm_model,svm_pred, X_train, y_train, X_test, y_test)

Train Result:
Accuracy Score: 85.25%
_______________________________________________
CLASSIFICATION REPORT:
                   0          1  accuracy  macro avg  weighted avg
precision   0.909091   0.820513  0.852459   0.864802      0.859720
recall      0.740741   0.941176  0.852459   0.840959      0.852459
f1-score    0.816327   0.876712  0.852459   0.846519      0.849984
support    27.000000  34.000000  0.852459  61.000000     61.000000
_______________________________________________
Confusion Matrix: 
 [[20  7]
 [ 2 32]]



In [13]:
#Result with new input
new_input = [37,	1,	2,	130,	250,	0,	1,	187,	0,	3.5,	0,	0,	2	]
svm_model.predict([new_input])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  "X does not have valid feature names, but"


array([0])

In [14]:
from sklearn.tree import DecisionTreeClassifier


tree_model = DecisionTreeClassifier(random_state=42)
tree_model.fit(X_train, y_train)
tree_pred = tree_model.predict(X_test)

print_result(tree_model,tree_pred, X_train, y_train, X_test, y_test)


Train Result:
Accuracy Score: 77.05%
_______________________________________________
CLASSIFICATION REPORT:
                   0          1  accuracy  macro avg  weighted avg
precision   0.709677   0.833333  0.770492   0.771505      0.778600
recall      0.814815   0.735294  0.770492   0.775054      0.770492
f1-score    0.758621   0.781250  0.770492   0.769935      0.771234
support    27.000000  34.000000  0.770492  61.000000     61.000000
_______________________________________________
Confusion Matrix: 
 [[22  5]
 [ 9 25]]



In [15]:
#Result with new input
new_input = [37,	1,	2,	130,	250,	0,	1,	187,	0,	3.5,	0,	0,	2	]
tree_model.predict([new_input])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([1])

## **Random Forest**

In [16]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV

rf_model = RandomForestClassifier(n_estimators=1000, random_state=42)
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)

print_result(rf_model,rf_pred, X_train, y_train, X_test, y_test)


Train Result:
Accuracy Score: 85.25%
_______________________________________________
CLASSIFICATION REPORT:
                   0          1  accuracy  macro avg  weighted avg
precision   0.846154   0.857143  0.852459   0.851648      0.852279
recall      0.814815   0.882353  0.852459   0.848584      0.852459
f1-score    0.830189   0.869565  0.852459   0.849877      0.852136
support    27.000000  34.000000  0.852459  61.000000     61.000000
_______________________________________________
Confusion Matrix: 
 [[22  5]
 [ 4 30]]



In [17]:
#Result with new input
new_input = [37,	1,	2,	130,	250,	0,	1,	187,	0,	3.5,	0,	0,	2	]
rf_model.predict([new_input])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([1])

## **XGBoost Classifer**

In [18]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(use_label_encoder=False)
xgb_model.fit(X_train, y_train)
xgb_model.fit(X_train, y_train)
xgb_pred = xgb_model.predict(X_test)

print_result(xgb_model,xgb_pred, X_train, y_train, X_test, y_test)

Train Result:
Accuracy Score: 85.25%
_______________________________________________
CLASSIFICATION REPORT:
                   0          1  accuracy  macro avg  weighted avg
precision   0.846154   0.857143  0.852459   0.851648      0.852279
recall      0.814815   0.882353  0.852459   0.848584      0.852459
f1-score    0.830189   0.869565  0.852459   0.849877      0.852136
support    27.000000  34.000000  0.852459  61.000000     61.000000
_______________________________________________
Confusion Matrix: 
 [[22  5]
 [ 4 30]]



## **Neural network**

In [25]:
from tensorflow.keras.utils import to_categorical
y_train_nn = to_categorical(y_train)

In [26]:
from tensorflow.keras import layers
from tensorflow.keras import models

In [27]:
# FFNN with relu
nn_model = models.Sequential()
nn_model.add(layers.Dense(15, activation='relu'))
nn_model.add(layers.Dense(10,activation='relu'))

nn_model.add(layers.Dense(2,activation='softmax'))


nn_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [28]:
nn_model.fit(X_train,y_train_nn,epochs=100, batch_size=30, verbose=2)

Epoch 1/100
9/9 - 1s - loss: 0.7533 - accuracy: 0.5413 - 748ms/epoch - 83ms/step
Epoch 2/100
9/9 - 0s - loss: 0.7257 - accuracy: 0.5413 - 19ms/epoch - 2ms/step
Epoch 3/100
9/9 - 0s - loss: 0.7061 - accuracy: 0.5413 - 18ms/epoch - 2ms/step
Epoch 4/100
9/9 - 0s - loss: 0.6893 - accuracy: 0.5496 - 20ms/epoch - 2ms/step
Epoch 5/100
9/9 - 0s - loss: 0.6765 - accuracy: 0.5413 - 20ms/epoch - 2ms/step
Epoch 6/100
9/9 - 0s - loss: 0.6628 - accuracy: 0.5785 - 17ms/epoch - 2ms/step
Epoch 7/100
9/9 - 0s - loss: 0.6506 - accuracy: 0.6074 - 17ms/epoch - 2ms/step
Epoch 8/100
9/9 - 0s - loss: 0.6397 - accuracy: 0.6281 - 34ms/epoch - 4ms/step
Epoch 9/100
9/9 - 0s - loss: 0.6263 - accuracy: 0.6570 - 23ms/epoch - 3ms/step
Epoch 10/100
9/9 - 0s - loss: 0.6144 - accuracy: 0.6736 - 19ms/epoch - 2ms/step
Epoch 11/100
9/9 - 0s - loss: 0.6020 - accuracy: 0.7107 - 28ms/epoch - 3ms/step
Epoch 12/100
9/9 - 0s - loss: 0.5891 - accuracy: 0.7355 - 31ms/epoch - 3ms/step
Epoch 13/100
9/9 - 0s - loss: 0.5775 - accuracy

In [29]:
n_pred = nn_model.predict(X_test, batch_size = 30)
nn_pred = n_pred.argmax(axis = 1)

print_result(nn_model,nn_pred, X_train, y_train_nn, X_test, y_test)

Train Result:
Accuracy Score: 88.52%
_______________________________________________
CLASSIFICATION REPORT:
                   0          1  accuracy  macro avg  weighted avg
precision   0.884615   0.885714  0.885246   0.885165      0.885228
recall      0.851852   0.911765  0.885246   0.881808      0.885246
f1-score    0.867925   0.898551  0.885246   0.883238      0.884995
support    27.000000  34.000000  0.885246  61.000000     61.000000
_______________________________________________
Confusion Matrix: 
 [[23  4]
 [ 3 31]]

